import sys
sys.path.append("")
import os
import yaml
import schedule
import threading
from threading import Thread
import time
import subprocess
import requests
import io
from telebot import types
import telebot
from dotenv import load_dotenv
load_dotenv()

from Utils.utils import *
from Utils.bot_utils import *
from src.PayBackTime import find_PBT_stocks
from src.trading_record import scrape_trading_data
from src.summarize_text import *
from src.Utils.logger import create_logger

logger = create_logger(logfile="logging/stock_bot.log")

data = config_parser(data_config_path='config/config.yaml')
user_data_path = data.get('user_data_path', None)
host = data.get('api_host', '0.0.0.0')
port = data.get('api_port', 8000)
BASE_URL = f"http://{host}:{port}"

check_server_status(url = BASE_URL, logger = logger)
    
try:
    TRADE_USER = os.getenv('TRADE_USER')
    TRADE_PASS = os.getenv('TRADE_PASS')
    TELEBOT_API = os.getenv('TELEBOT_API')
except:
    create_env_file()
    print('Please specify config in .env file, your bot token is generated by @BotFather')
    exit(1)

bot = telebot.TeleBot(TELEBOT_API)

@bot.message_handler(commands=['start'])
def start(message):
    start_commands = read_commands_from_file(data.get('start_commands_path'))
    help_commands = read_commands_from_file(data.get('help_commands_path'))
    bot.send_message(message.chat.id, f"{start_commands}{help_commands}")

@bot.message_handler(commands=['help'])
def help(message):
    help_commands = read_commands_from_file(data.get('help_commands_path'))
    bot.send_message(message.chat.id, help_commands)

@bot.message_handler(commands=['rate', 'risk', 'pbt', 'mulpattern', 'pattern', 'snr', 'buysellanalyze'])
def ask_for_symbol(message):
    markup = types.ForceReply(selective=False)
    bot.reply_to(message, "Please enter the stock symbol:", reply_markup=markup)
    if message.text == '/rate':
        bot.register_next_step_handler(message, rate)
    elif message.text == '/risk':
        bot.register_next_step_handler(message, calculate_risk)
    elif message.text == '/pbt':
        bot.register_next_step_handler(message, get_paybacktime)
    elif message.text == '/snr':
        bot.register_next_step_handler(message, get_support_resistance)
    elif message.text == '/buysellanalyze':
        bot.register_next_step_handler(message, get_buysell_analyze)
    else:  # message.text in ['/mulpattern', '/pattern']:
        bot.register_next_step_handler(message, ask_pattern_stock, message.text)

@validate_symbol_decorator(bot)
def ask_pattern_stock(message, command):
    symbol = message.text.upper()
    markup = types.ForceReply(selective=False)
    bot.reply_to(message, "Please enter the start_date (YYYY-mm-dd):", reply_markup=markup)
    if command == '/mulpattern':
        bot.register_next_step_handler(message, find_similar_pattern_multi_dimension, symbol)
    else:  # command == '/pattern':
        bot.register_next_step_handler(message, find_similar_pattern, symbol)

@bot.message_handler(commands=['masterquest'])
def ask_for_question(message):
    if not validate_mrzaizai2k_user(message.chat.id):
        bot.send_message(message.chat.id, "This command can just be used by the owner (mrzaizai2k).\nIf you want to use this, clone the git repo and modify the code")
        return
    markup = types.ForceReply(selective=False)
    bot.reply_to(message, "Please enter the question:", reply_markup=markup)
    bot.register_next_step_handler(message, masterquest)

def masterquest(message):
    query = message.text
    masterquest_url = data.get('masterquest_url')
    try:
        response = requests.post(masterquest_url, json={'query': query})
        logger.debug(msg=f"Result: {response.json()}")
        bot.reply_to(message, f"The answer from {response.json()['model_type']}: \n{response.json()['result']}")
    except Exception as e:
        logger.debug(msg=f"Error on LLM and RAG system: {e}")
        print('You might need to run the LLM with RAG system on port 8083')
        bot.send_message(message.chat.id, "Error on connecting the LLM and RAG system")

@bot.message_handler(commands=['updatevectordb'])
def updatevectordb(message):
    if not validate_mrzaizai2k_user(message.chat.id):
        bot.send_message(message.chat.id, "This command can just be used by the owner (mrzaizai2k).\nIf you want to use this, clone the git repo and modify the code")
        return
    updatevectordb_url = data.get('updatevectordb_url')
    response = requests.post(updatevectordb_url)
    if response.status_code == 200:
        logger.debug(msg="Update Vector DB Successful: Update was successful")
        bot.send_message(message.chat.id, "Update was successful")
    else:
        logger.debug(msg=f"Update Vector DB Failed: {response.status_code} - {response.json()['message']}")
        bot.send_message(message.chat.id, f"Update failed: {response.json()['message']}")

def find_similar_pattern(message, symbol):
    start_date = message.text
    bot.send_message(message.chat.id, "Please wait. This process can take several minutes")
    try:
        response = requests.post(
            f"{BASE_URL}/stocks/pattern",
            json={"symbol": symbol, "start_date": start_date}
        )
        response.raise_for_status()
        data = response.json()
        image_data = bytes.fromhex(data["image"])
        bot.send_photo(message.chat.id, io.BytesIO(image_data))
        bot.send_message(message.chat.id, data["message"])
    except requests.exceptions.RequestException as e:
        logger.debug(msg=f"Error calling /stocks/pattern: {str(e)}")
        bot.send_message(message.chat.id, f"Error finding pattern: {str(e)}")

def find_similar_pattern_multi_dimension(message, symbol):
    start_date = message.text
    bot.send_message(message.chat.id, "Please wait. This process can take several minutes")
    try:
        response = requests.post(
            f"{BASE_URL}/stocks/multi-pattern",
            json={"symbol": symbol, "start_date": start_date}
        )
        response.raise_for_status()
        data = response.json()
        image_data = bytes.fromhex(data["image"])
        bot.send_photo(message.chat.id, io.BytesIO(image_data))
        bot.send_message(message.chat.id, data["message"])
    except requests.exceptions.RequestException as e:
        logger.debug(msg=f"Error calling /stocks/multi-pattern: {str(e)}")
        bot.send_message(message.chat.id, f"Error finding multi-dimension pattern: {str(e)}")

@validate_symbol_decorator(bot)
def get_paybacktime(message):
    symbol = message.text.upper()
    bot.send_message(message.chat.id, "Please wait. This process can take several minutes")
    try:
        response = requests.post(
            f"{BASE_URL}/stocks/paybacktime",
            json={"symbol": symbol}
        )
        response.raise_for_status()
        report = response.json()["report"]
        bot.send_message(message.chat.id, report)
        logger.debug(msg=f"Paybacktime report: {report}")
    except requests.exceptions.RequestException as e:
        logger.debug(msg=f"Error calling /stocks/paybacktime: {str(e)}")
        bot.send_message(message.chat.id, f"Error calculating payback time: {str(e)}")

@validate_symbol_decorator(bot)
def get_buysell_analyze(message):
    symbol = message.text.upper()
    try:
        response = requests.post(
            f"{BASE_URL}/stocks/buy-sell-analyze",
            json={"symbol": symbol}
        )
        response.raise_for_status()
        data = response.json()
        image_data = bytes.fromhex(data["image"])
        bot.send_photo(message.chat.id, io.BytesIO(image_data))
        bot.send_message(message.chat.id, data["message"])
    except requests.exceptions.RequestException as e:
        logger.debug(msg=f"Error calling /stocks/buy-sell-analyze: {str(e)}")
        bot.send_message(message.chat.id, f"Error analyzing buy/sell: {str(e)}")

@validate_symbol_decorator(bot)
def get_support_resistance(message):
    symbol = message.text.upper()
    try:
        response = requests.post(
            f"{BASE_URL}/stocks/support-resistance",
            json={"symbol": symbol}
        )
        response.raise_for_status()
        report = response.json()["report"]
        bot.send_message(message.chat.id, report)
        logger.debug(msg=f"Support/Resistance report: {report}")
    except requests.exceptions.RequestException as e:
        logger.debug(msg=f"Error calling /stocks/support-resistance: {str(e)}")
        bot.send_message(message.chat.id, f"Error calculating support/resistance: {str(e)}")

@validate_symbol_decorator(bot)
def calculate_risk(message):
    symbol = message.text.upper()
    try:
        response = requests.post(
            f"{BASE_URL}/stocks/risk",
            json={"symbol": symbol}
        )
        response.raise_for_status()
        report = response.json()["report"]
        bot.send_message(message.chat.id, report)
        logger.debug(msg=f"Risk report: {report}")
    except requests.exceptions.RequestException as e:
        logger.debug(msg=f"Error calling /stocks/risk: {str(e)}")
        bot.send_message(message.chat.id, f"Error calculating risk: {str(e)}")

@validate_symbol_decorator(bot)
def rate(message):
    symbol = message.text.upper()
    try:
        response = requests.post(
            f"{BASE_URL}/stocks/rate",
            json={"symbol": symbol}
        )
        response.raise_for_status()
        report = response.json()["report"]
        bot.send_message(message.chat.id, report)
        logger.debug(msg=f"Rating report: {report}")
    except requests.exceptions.RequestException as e:
        logger.debug(msg=f"Error calling /stocks/rate: {str(e)}")
        bot.send_message(message.chat.id, f"Error rating stock: {str(e)}")

@bot.message_handler(commands=['findpbt'])
def findpbt(message):
    bot.send_message(message.chat.id, "Please wait. This process can take several minutes")
    try:
        response = requests.get(f"{BASE_URL}/stocks/find-paybacktime-stocks")
        response.raise_for_status()
        stocks = response.json()["stocks"]
        bot.send_message(message.chat.id, f"The Paybacktime stocks are {', '.join(stocks)}")
        logger.debug(msg=f"Paybacktime stocks: {stocks}")
    except requests.exceptions.RequestException as e:
        logger.debug(msg=f"Error calling /stocks/find-paybacktime-stocks: {str(e)}")
        bot.send_message(message.chat.id, f"Error finding payback time stocks: {str(e)}")

@bot.message_handler(commands=['findmyfav'])
def findmyfav(message):
    try:
        response = requests.get(f"{BASE_URL}/stocks/find-favorite-stocks")
        response.raise_for_status()
        stocks = response.json()["stocks"]
        bot.send_message(message.chat.id, f"The stocks most suitable for you are: {stocks}")
        logger.debug(msg=f"Suitable stocks: {stocks}")
    except requests.exceptions.RequestException as e:
        logger.debug(msg=f"Error calling /stocks/find-favorite-stocks: {str(e)}")
        bot.send_message(message.chat.id, f"Error finding favorite stocks: {str(e)}")

@bot.message_handler(commands=['findbestmotif'])
def findbestmotif(message):
    bot.send_message(message.chat.id, "Please wait. This process can take several minutes")
    try:
        response = requests.get(f"{BASE_URL}/stocks/find-best-motif")
        response.raise_for_status()
        report = response.json()["report"]
        bot.send_message(message.chat.id, report)
        logger.debug(msg=f"Best motif report: {report}")
    except requests.exceptions.RequestException as e:
        logger.debug(msg=f"Error calling /stocks/find-best-motif: {str(e)}")
        bot.send_message(message.chat.id, f"Error finding best motif: {str(e)}")

@bot.message_handler(commands=['winlossanalyze'])
def analyze_winloss(message):
    try:
        response = requests.get(f"{BASE_URL}/stocks/win-loss-analyze")
        response.raise_for_status()
        report = response.json()["report"]
        bot.send_message(message.chat.id, report)
        logger.debug(msg=f"WinLoss report: {report}")
    except requests.exceptions.RequestException as e:
        logger.debug(msg=f"Error calling /stocks/win-loss-analyze: {str(e)}")
        bot.send_message(message.chat.id, f"Error analyzing win/loss: {str(e)}")

@bot.message_handler(commands=['watchlist'])
def handle_watchlist(message):
    markup = types.ReplyKeyboardMarkup(row_width=1, one_time_keyboard=True)
    watch_button = types.KeyboardButton('Watch')
    add_button = types.KeyboardButton('Add')
    remove_button = types.KeyboardButton('Remove')
    markup.add(watch_button, add_button, remove_button)
    bot.send_message(message.chat.id, "Choose an action:", reply_markup=markup)
    bot.register_next_step_handler(message, process_button_click)

def process_button_click(message):
    user_action = message.text.lower()
    if user_action == 'watch':
        user_db = UserDatabase(user_data_path=user_data_path)
        watchlist = user_db.get_watch_list(user_id=message.chat.id)
        bot.send_message(message.chat.id, f"Your watchlist: {watchlist}")
    elif user_action == 'add':
        bot.send_message(message.chat.id, "Enter the stock name to add:\n VD: VIX")
        bot.register_next_step_handler(message, process_add_stock)
    elif user_action == 'remove':
        bot.send_message(message.chat.id, "Enter the stock name to remove:\n VD: VIX")
        bot.register_next_step_handler(message, process_remove_stock)
    else:
        bot.send_message(message.chat.id, "Invalid option. Please choose a valid action.")

@validate_symbol_decorator(bot)
def process_add_stock(message):
    symbol = message.text.upper()
    user_db = UserDatabase(user_data_path=user_data_path)
    watchlist = user_db.get_watch_list(user_id=message.chat.id)
    watchlist.append(symbol)
    user_db.save_watch_list(user_id=message.chat.id, watch_list=watchlist)
    bot.send_message(message.chat.id, f"{symbol} added to your watchlist. Updated watchlist: {watchlist}")
    logger.debug(msg=f"{symbol} added to your watchlist. Updated watchlist: {watchlist}")

@validate_symbol_decorator(bot)
def process_remove_stock(message):
    symbol = message.text.upper()
    user_db = UserDatabase(user_data_path=user_data_path)
    watchlist = user_db.get_watch_list(user_id=message.chat.id)
    if symbol in watchlist:
        watchlist.remove(symbol)
        user_db.save_watch_list(user_id=message.chat.id, watch_list=watchlist)
        bot.send_message(message.chat.id, f"{symbol} removed from your watchlist. Updated watchlist: {watchlist}")
        logger.debug(msg=f"{symbol} removed from your watchlist. Updated watchlist: {watchlist}")
    else:
        bot.send_message(message.chat.id, f"{symbol} not found in your watchlist.")
        logger.debug(msg=f"{symbol} not found in your watchlist.")

@bot.message_handler(commands=['remote'])
def open_vscode_tunnel(message):
    if not validate_mrzaizai2k_user(message.chat.id):
        mess = "This command can just be used by the owner (mrzaizai2k).\nIf you want to use this, clone the git repo and modify the code"
        bot.send_message(message.chat.id, mess)
        logger.info(mess)
        return
    bot.reply_to(message, "VS Code remote tunnel Opening...")
    Thread(target=run_vscode_tunnel, args=(bot, message)).start()

def warning_stock():
    times = data.get('times', [])
    functions = [warning_macd, warningpricevsma, warningsnr, warningbigday]
    user_db = UserDatabase(user_data_path=user_data_path)
    user_list = user_db.get_users_for_warning()
    for time_str in times:
        for func in functions:
            for user in user_list:
                watchlist = user_db.get_watch_list(user_id=user)
                if func in [warningsnr, warningpricevsma]:
                    schedule.every().day.at(f"{time_str}").do(func, bot=bot, watchlist=watchlist, user_id=user, data_config=data)
                else:
                    schedule.every().day.at(f"{time_str}").do(func, bot=bot, watchlist=watchlist, user_id=user)

def summary_news_daily(max_retries=3, wait_time=60):
    retries = 0
    user_db = UserDatabase(user_data_path=user_data_path)
    all_stocks = user_db.get_all_watchlist()
    stock_news_db = StockNewsDatabase(summary_news_data_path=data.get('summary_news_data_path'))
    while retries < max_retries:
        try:
            stock_news_db.update_news(watch_list=all_stocks)
            logger.debug(msg='Finish updating daily news summary!')
            break
        except Exception as e:
            logger.debug(msg=f'Error updating daily news summary {e}')
            time.sleep(wait_time)
            retries += 1
    else:
        logger.debug(msg=f"Max retries reached. Unable to update daily news summary after {max_retries} attempts.")

def send_summary_news():
    user_db = UserDatabase(user_data_path=user_data_path)
    user_list = user_db.get_users_for_warning()
    stock_news_db = StockNewsDatabase(summary_news_data_path=data.get('summary_news_data_path'))
    for user in user_list:
        watchlist = user_db.get_watch_list(user_id=user)
        all_stocks_list = stock_news_db.get_all_stocks()
        common_stocks = list(set(watchlist) & set(all_stocks_list))
        summary_news = "Đây là bản tin tổng hợp hàng ngày"
        for stock in common_stocks:
            news_text, news_url = stock_news_db.extract_text_for_stock(stock)
            summary_news += f"\nStock: {stock}"
            summary_news += f"\n{news_text}"
            summary_news += f"\nLink: {news_url}"
            summary_news += f"\n-------------"
        bot.send_message(user, summary_news)
        top_news = f"\nTin nổi bật\n"
        top_news += f"\n{stock_news_db.get_top_news()}"
        bot.send_message(user, top_news)

@bot.callback_query_handler(func=lambda call: call.data.startswith('checklist_toggle__'))
def checklist_button_click(call):
    index = int(call.data.replace('checklist_toggle__', ''))
    if not call.message.reply_markup:
        print(f'no reply_markup for message_id {call.message.message_id} and chat_id {call.message.chat.id}')
        return
    inline_keyboard = call.message.reply_markup.keyboard
    button = inline_keyboard[index][0]
    button.text = toggle_button_state(button.text)
    bot.edit_message_text(
        chat_id=call.message.chat.id,
        message_id=call.message.message_id,
        text='Click to toggle',
        reply_markup=types.InlineKeyboardMarkup(inline_keyboard),
    )

@bot.message_handler(commands=['summarynewsurl'])
def ask_for_link(message):
    markup = types.ForceReply(selective=False)
    bot.reply_to(message, "Please paste the news url for summarization:", reply_markup=markup)
    bot.register_next_step_handler(message, summary_news_from_links)

def summary_news_from_links(message):
    news_url = message.text
    try:
        response = requests.post(
            f"{BASE_URL}/stocks/summary-news-url",
            json={"url": news_url}
        )
        response.raise_for_status()
        summary = response.json()["summary"]
        bot.send_message(message.chat.id, f"Here's your summary news:\n{summary}")
        logger.debug(msg=f"Summary news: {summary}")
    except requests.exceptions.RequestException as e:
        logger.debug(msg=f"Error calling /stocks/summary-news-url: {str(e)}")
        bot.send_message(message.chat.id, f"Error summarizing news: {str(e)}")

@bot.message_handler(commands=['scrape'])
def scrape_data(message):
    if not validate_mrzaizai2k_user(message.chat.id):
        mess = "This command can just be used by the owner (mrzaizai2k).\nIf you want to use this, clone the git repo and modify the code"
        bot.send_message(message.chat.id, mess)
        logger.info(mess)
        return
    bot.send_message(message.chat.id, "Please wait. This process can take several minutes")
    scrape_trading_data(user_name=TRADE_USER, password=TRADE_PASS)
    bot.send_message(message.chat.id, "Done scraping trading data!")
    logger.info(msg="Done scraping trading data!")
    summary_news_daily()
    bot.send_message(message.chat.id, "Done updating news!")
    logger.info(msg="Done updating news!")

@bot.message_handler(commands=['log'])
def send_log(message):
    if not validate_mrzaizai2k_user(message.chat.id):
        mess = "This command can just be used by the owner (mrzaizai2k).\nIf you want to use this, clone the git repo and modify the code"
        bot.send_message(message.chat.id, mess)
        logger.info(mess)
        return
    log_file_path = data.get('log_file_path')
    try:
        with open(log_file_path, 'rb') as log_file:
            bot.send_document(message.chat.id, log_file)
    except FileNotFoundError:
        bot.send_message(message.chat.id, "Log file not found.")
    except Exception as e:
        bot.send_message(message.chat.id, f"An error occurred: {e}")

@bot.message_handler(content_types=['audio', 'voice'])
def summarize_sound(message):
    bot.send_message(message.chat.id, "Processing...")
    file_id = message.audio.file_id if message.content_type == 'audio' else message.voice.file_id
    file_info = bot.get_file(file_id)
    downloaded_file = bot.download_file(file_info.file_path)
    file_path = f'data/{file_id}.mp3'
    with open(file_path, 'wb') as new_file:
        new_file.write(downloaded_file)
    speech_to_text = SpeechSummaryProcessor(audio_path=file_path)
    try:
        text = speech_to_text.generate_speech_to_text()
        logger.debug(msg=f"Original voice:\n{text}")
        bot.reply_to(message, f"Here's your note:\n{text}")
    except Exception as e:
        logger.debug(msg=f"Error on understanding sound: {e}")
        text = None
        bot.reply_to(message, "Sorry, I can't understand your voice. Please try again!")
    os.remove(file_path)
    if text is None:
        return
    reply_markup = handle_checklist(text)
    bot.send_message(message.chat.id, 'Click to toggle', reply_markup=relay_markup)
    tasks_list = speech_to_text.get_task_list()
    logger.debug(msg=f'tasks_list: {tasks_list}')
    if tasks_list is not None and validate_mrzaizai2k_user(message.chat.id):
        sync_task_to_todo(tasks_list)
        bot.send_message(message.chat.id, "The tasks have been integrated to Microsoft To Do!")
        logger.info(msg="The tasks have been integrated to Microsoft To Do!")

@bot.message_handler(func=lambda message: True)
def echo(message):
    response_message = "Apologies, I didn't understand that command. 😕\nPlease type /help to see the list of available commands."
    bot.send_message(message.chat.id, response_message)

def main():
    warning_stock()
    schedule.every().day.at(data.get('scape_trading_data_time')).do(scrape_trading_data, user_name=TRADE_USER, password=TRADE_PASS)
    schedule.every().day.at(data.get('news_summary_time')).do(summary_news_daily)
    schedule.every().day.at(data.get('send_news_summary_time')).do(send_summary_news)
    Thread(target=schedule_checker).start()
    while True:
        try:
            bot.infinity_polling(logger_level=None)
        except Exception as e:
            logger.debug(msg=f"An error occurred: {str(e)}")
            logger.debug(msg="Resetting the bot in 3 seconds...")
            time.sleep(3)
            main()
        finally:
            schedule.clear()

if __name__ == "__main__":
    main()